name: Typescript Unit Test
on: [push, pull_request]

jobs:
  run:
    name: Node ${{ matrix.node }} on Ubuntu latest
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node: [12]

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Set up npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci || { echo "NPM install failed. Check logs."; exit 1; }

      - name: Run compile
        run: npm run compile-all

      - name: Run test
        run: npm run test

      - name: Upload npm debug log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-logs
          path: ~/.npm/_logs/*.log

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"